import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

type RequirementGroup = Readonly<{
  count: number;
  evidence: string;
  prefix: string;
  qualification: string;
}>;

const groups: readonly RequirementGroup[] = [
  // Withdrawn on 2026-09-08 with the SaaS shell (ADR 2026-09-08-single-operator-kernel): FR-AUTH, FR-TEN, FR-TEAM, FR-CUS, FR-ENT, FR-BILL, FR-RATE.
  { count: 8, evidence: "policy contract, persistence, service, governed-action, diff, UI read-model, self-policy, and gate 3/4 PostgreSQL approval-race and single-active-revision tests", prefix: "FR-POL", qualification: "local unit/static and isolated PostgreSQL proof; maker-checker separation withdrawn with identity" },
  { count: 11, evidence: "validator CLI, discovery, engine, runner, golden baseline, semantic check-kind matrices, public artifact, self-policy, and benchmark checks", prefix: "FR-VAL", qualification: "local executable proof" },
  { count: 8, evidence: "evidence transport, bearer-token request context, service, compatibility, persistence adapter, persistence, route, and UI read-model tests", prefix: "FR-EVD", qualification: "local unit/contract proof; live PostgreSQL retention and ingestion proof pending" },
  { count: 6, evidence: "exception contract, persistence, signing-key, validator-consumption, gate 4 decision-race, and reserved-export tests", prefix: "FR-EXC", qualification: "local unit/cryptographic proof; production export custody intentionally unavailable" },
  { count: 6, evidence: "audit, governed-action rollback, gate 3 transaction rollback, correlation proxy, request logging, redaction, and safe read-model tests", prefix: "FR-AUD", qualification: "local unit/schema proof; full hosted request tracing pending" },
  { count: 9, evidence: "route/UI contracts, read models, production build, and desktop/320px Playwright axe checks over every page", prefix: "FR-UI", qualification: "local build/browser proof" },
  // Validator rule language, PRP docs/prp/2026-09-09-validator-rule-language.md, ADRs docs/adr/2026-09-09-*.md.
  { count: 5, evidence: "policy schema layers/superRefine tests, layers expansion and fast-check order property, compatibility expansion, engine guard, runner expansion, self-policy rewrite with bite proof", prefix: "FR-LAY", qualification: "local unit/static proof; existing digests and golden fixture unchanged by assertion" },
  { count: 4, evidence: "argument-shape prover tests, call-argument fixture matrix, compatibility grammar tests, self-policy rule tenant-queries-carry-workspace with missing-key and opaque-spread bite proofs", prefix: "FR-ARG", qualification: "local unit/static proof; intra-procedural only" },
  { count: 5, evidence: "state-transition fixture matrix, compatibility two-subject grammar tests, self-policy rule policy-revision-state-is-governed with rogue-writer and unlisted-pair bite proofs", prefix: "FR-STA", qualification: "local unit/static proof; literal predicates only" },
  { count: 6, evidence: "ingress fixture matrix incl. closure, monotone widening, factory-bound export, route test via mocked runtime, five self-policy verb rules with request.json escape and factory-bound proof bites", prefix: "FR-ING", qualification: "local unit/static proof; intra-procedural, allowed-call results trusted by declaration" },
  { count: 5, evidence: "self-policy uses layers and all three kinds, contracts regenerated and checked, README and validator docs examples, this traceability, benchmark rules per kind under 30 s and 1 GiB", prefix: "FR-DOG", qualification: "local executable proof; benchmark corpus has no calls, so numbers are a floor for the new evaluators" },
];

const rows = groups.flatMap((group) => Array.from({ length: group.count }, (_, index) => {
  const id = `${group.prefix}-${String(index + 1).padStart(3, "0")}`;
  return `| ${id} | ${group.evidence} | ${group.qualification} |`;
}));
const document = `# Functional requirement traceability\n\nGenerated by \`npm run traceability:generate\`. Each functional requirement has an executable test suite or deterministic static check. The qualification column prevents local/mocked evidence from being mistaken for hosted, live-provider, or production proof.\n\n| Requirement | Executable or deterministic evidence | Qualification boundary |\n| --- | --- | --- |\n${rows.join("\n")}\n`;
const output = path.resolve("docs", "TRACEABILITY.md");
await mkdir(path.dirname(output), { recursive: true });
await writeFile(output, document, "utf8");
process.stdout.write(`traceability: wrote ${String(rows.length)} functional requirement mappings\n`);
