import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

import { canonicalJson, type Sha256Digest } from "@kernel-zero/domain";
import {
  EXCEPTION_GRANT_SET_MEDIA_TYPE,
  REPOSITORY_POLICY_MEDIA_TYPE,
  REPOSITORY_EVIDENCE_MEDIA_TYPE,
  canonicalEvidenceDigest,
  deriveEvidenceSummary,
  exceptionGrantSetJsonSchema,
  findingIdentity,
  findingMessage,
  repositoryEvidenceJsonSchema,
  repositoryPolicyJsonSchema,
} from "@kernel-zero/contracts";

const digest = (digit: "1" | "3" | "5"): Sha256Digest => `sha256:${digit.repeat(64)}`;
const policyExample = {
  apiVersion: "kernel-zero.dev/v1",
  kind: "RepositoryPolicy",
  metadata: { description: "Repository architecture rules", name: "service-boundaries", revision: 1 },
  scope: { exclude: ["**/*.generated.ts", "**/fixtures/**"], include: ["apps/**/*.ts", "apps/**/*.tsx", "packages/**/*.ts"], languages: ["typescript", "tsx"] },
  rules: [{
    check: { deny: ["module:@kernel-zero/persistence", "module:@prisma/client"], from: ["apps/control/**"], kind: "forbid-import-edge" },
    id: "layers-no-ui-db", level: "error", remediation: "Call an application service through a validated boundary.", title: "UI cannot import persistence",
  }],
};
const exceptionExample = {
  apiVersion: "kernel-zero.dev/exceptions/v1", kind: "ExceptionGrantSet",
  workspace: "0195f000-0000-7000-8000-000000000002", policyDigest: digest("1"),
  generatedAt: "2026-01-15T12:00:00.000Z", expiresAt: "2026-01-16T12:00:00.000Z",
  grants: [{ exceptionId: "0195f000-0000-7000-8000-000000000003", ruleId: "layers-no-ui-db", fingerprint: digest("3"), validUntil: "2026-02-01T00:00:00.000Z" }],
  integrity: { algorithm: "sha256", digest: digest("5") },
  signature: { algorithm: "ed25519", keyId: "workspace-key-id", value: Buffer.alloc(64).toString("base64") },
};
const evidenceLocation = { endColumn: 44, endLine: 8, startColumn: 1, startLine: 8 };
const evidenceFindingIdentity = findingIdentity({
  location: evidenceLocation, messageCode: "DENIED_IMPORT", path: "apps/control/ui/page.tsx",
  policyDigest: digest("1"), ruleId: "layers-no-ui-db", subject: "@prisma/client",
});
const evidenceFinding = {
  ...evidenceFindingIdentity, exceptionId: null, level: "error" as const, location: evidenceLocation,
  message: findingMessage("DENIED_IMPORT"), messageCode: "DENIED_IMPORT" as const,
  path: "apps/control/ui/page.tsx", ruleId: "layers-no-ui-db", subject: "@prisma/client",
};
const evidenceBase = {
  apiVersion: "kernel-zero.dev/evidence/v1" as const, exceptionBundleDigest: null,
  findings: [evidenceFinding], generatedAt: "2026-01-15T12:00:00.000Z",
  kind: "RepositoryEvidence" as const,
  policy: { digest: digest("1"), name: "service-boundaries", revision: 1 },
  result: { ...deriveEvidenceSummary([evidenceFinding], 42), durationMs: 1_250 },
  runId: "0195f000-0000-7000-8000-000000000001", signature: null,
  subject: { manifestDigest: digest("1"), repository: "example/service", revision: "git:0123456789abcdef0123456789abcdef01234567" },
  tool: { name: "kernel-zero-validator" as const, version: "1.0.0" },
  workspace: "0195f000-0000-7000-8000-000000000002",
};
const evidenceExample = { ...evidenceBase, integrity: { algorithm: "sha256" as const, digest: canonicalEvidenceDigest(evidenceBase) } };

const outputs = new Map<string, string>([
  ["docs/contracts/repository-policy-v1.schema.json", `${JSON.stringify(repositoryPolicyJsonSchema(), null, 2)}\n`],
  ["docs/contracts/exception-grant-set-v1.schema.json", `${JSON.stringify(exceptionGrantSetJsonSchema(), null, 2)}\n`],
  ["docs/contracts/repository-evidence-v1.schema.json", `${JSON.stringify(repositoryEvidenceJsonSchema(), null, 2)}\n`],
  ["docs/contracts/examples/repository-policy-v1.json", `${canonicalJson(policyExample)}\n`],
  ["docs/contracts/examples/exception-grant-set-v1.json", `${canonicalJson(exceptionExample)}\n`],
  ["docs/contracts/examples/repository-evidence-v1.json", `${canonicalJson(evidenceExample)}\n`],
  ["docs/contracts/malformed/repository-policy-unknown-field.json", `${JSON.stringify({ ...policyExample, command: "npm test" }, null, 2)}\n`],
  ["docs/contracts/malformed/repository-policy-path-escape.json", `${JSON.stringify({ ...policyExample, scope: { ...policyExample.scope, include: ["../private.ts"] } }, null, 2)}\n`],
  ["docs/contracts/malformed/exception-grant-set-private-data.json", `${JSON.stringify({ ...exceptionExample, rationale: "must never be exported" }, null, 2)}\n`],
  ["docs/contracts/malformed/repository-evidence-source-content.json", `${JSON.stringify({ ...evidenceExample, source: "private source text" }, null, 2)}\n`],
  ["docs/contracts/README.md", `# Public contracts\n\nGenerated by \`npm run contracts:generate\`. Do not hand-edit generated files.\n\n## RepositoryPolicy v1\n\nMedia type: \`${REPOSITORY_POLICY_MEDIA_TYPE}\`\n\nA strict, non-executable repository policy. Unknown fields, unknown check kinds, path escapes, duplicate IDs, arbitrary regular-expression fields, and unsupported languages are rejected. Canonical policy bytes use RFC 8785 before SHA-256.\n\nThe closed check kinds are \`forbid-import-edge\`, \`require-import\`, \`restrict-call-site\`, \`require-export-keys\`, \`require-tenant-parameter\`, \`require-boundary-parse\`, and \`require-governed-operation\`.\n\n## RepositoryEvidence v1\n\nMedia type: \`${REPOSITORY_EVIDENCE_MEDIA_TYPE}\`\n\nEvidence contains normalized findings and repository metadata, never source. The required check-specific subject lets ingestion recompute each fingerprint, location-sensitive ID, and closed safe message. Integrity excludes run ID, generation time, diagnostic duration, integrity, and signature.\n\n## ExceptionGrantSet v1\n\nMedia type: \`${EXCEPTION_GRANT_SET_MEDIA_TYPE}\`\n\nBundles contain opaque grant IDs and deterministic matching fields only. Grants are sorted by exception ID. Lifetime is at most 24 hours and never extends a grant. Integrity omits \`integrity\` and \`signature\`; an Ed25519 signature covers the raw 32-byte SHA-256 digest.\n`],
]);

const check = process.argv.includes("--check");
const drift: string[] = [];
for (const [relativePath, content] of outputs) {
  const path = resolve(relativePath);
  if (check) {
    let existing = "";
    try { existing = readFileSync(path, "utf8"); } catch { drift.push(relativePath); continue; }
    if (existing !== content) drift.push(relativePath);
  } else {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content, "utf8");
  }
}
if (drift.length > 0) {
  process.stderr.write(`Generated contract drift: ${drift.join(", ")}\n`);
  process.exitCode = 1;
}
