import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

type RequirementGroup = Readonly<{
  count: number;
  evidence: string;
  prefix: string;
  qualification: string;
}>;

const groups: readonly RequirementGroup[] = [
  // Withdrawn on 2026-09-08 with the SaaS shell (ADR 2026-09-08-single-operator-kernel): FR-AUTH, FR-TEN, FR-TEAM, FR-CUS, FR-ENT, FR-BILL, FR-RATE.
  { count: 8, evidence: "policy contract, persistence, service, governed-action, diff, UI read-model, self-policy, and gate 3/4 PostgreSQL approval-race and single-active-revision tests", prefix: "FR-POL", qualification: "local unit/static and isolated PostgreSQL proof; maker-checker separation withdrawn with identity" },
  { count: 11, evidence: "validator CLI, discovery, engine, runner, golden baseline, semantic check-kind matrices, public artifact, self-policy, and benchmark checks", prefix: "FR-VAL", qualification: "local executable proof" },
  { count: 8, evidence: "evidence transport, bearer-token request context, service, compatibility, persistence adapter, persistence, route, and UI read-model tests", prefix: "FR-EVD", qualification: "local unit/contract proof; live PostgreSQL retention and ingestion proof pending" },
  { count: 6, evidence: "exception contract, persistence, signing-key, validator-consumption, gate 4 decision-race, and reserved-export tests", prefix: "FR-EXC", qualification: "local unit/cryptographic proof; production export custody intentionally unavailable" },
  { count: 6, evidence: "audit, governed-action rollback, gate 3 transaction rollback, correlation proxy, request logging, redaction, and safe read-model tests", prefix: "FR-AUD", qualification: "local unit/schema proof; full hosted request tracing pending" },
  { count: 9, evidence: "route/UI contracts, read models, production build, and desktop/320px Playwright axe checks over every page", prefix: "FR-UI", qualification: "local build/browser proof" },
];

const rows = groups.flatMap((group) => Array.from({ length: group.count }, (_, index) => {
  const id = `${group.prefix}-${String(index + 1).padStart(3, "0")}`;
  return `| ${id} | ${group.evidence} | ${group.qualification} |`;
}));
const document = `# Functional requirement traceability\n\nGenerated by \`npm run traceability:generate\`. Each functional requirement has an executable test suite or deterministic static check. The qualification column prevents local/mocked evidence from being mistaken for hosted, live-provider, or production proof.\n\n| Requirement | Executable or deterministic evidence | Qualification boundary |\n| --- | --- | --- |\n${rows.join("\n")}\n`;
const output = path.resolve("docs", "TRACEABILITY.md");
await mkdir(path.dirname(output), { recursive: true });
await writeFile(output, document, "utf8");
process.stdout.write(`traceability: wrote ${String(rows.length)} functional requirement mappings\n`);
